openapi: 3.0.3
info:
  version: "1.0.0"
  title: Astro Search API
  description: 「Astro Search」用のAPI

servers:
  - url: http://localhost:8080
    description: Local development server
  - url: https://dev.example.com/api
    description: Development environment
  - url: https://api.example.com
    description: Production environment

paths:
  /map:
    get:
      summary: 場所を検索する
      description: クエリ文字列に基づき、Google Places APIを使用して場所の候補を取得します。
      検索キーワードはクエリパラメータ `query` で指定します。
      parameters:
        - name: query
          in: query
          description: 検索キーワード（例：東京タワー）
          required: true
          schema:
            type: string
      responses:
        "200":
          description: 検索結果
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      type: object
                      properties:
                        place_id:
                          type: string
                          description: Google Places API の Place ID
                        name:
                          type: string
                          description: 例：東京タワー
                        address:
                          type: string
                          description: 例：東京都港区芝公園4丁目2-8
        "400":
          description: パラメータエラー

  /map/{place_id}:
    get:
      summary: 場所の詳細を取得する
      description: 指定された Place ID に対して、緯度・経度・住所などの詳細情報を取得します。
      parameters:
        - name: place_id
          in: path
          required: true
          description: Google Places API の Place ID
          schema:
            type: string
      responses:
        "200":
          description: 詳細情報
          content:
            application/json:
              schema:
                type: object
                properties:
                  place_id:
                    type: string
                  name:
                    type: string
                  address:
                    type: string
                  latitude:
                    type: number
                    format: float
                    description: 緯度
                  longitude:
                    type: number
                    format: float
                    description: 経度
                description: Placeholder for place details
        "404":
          description: Place ID が見つかりません
